packages:
  - .
  - packages/server
  - packages/web
  - packages/ios
  - packages/whoop-whoop
  - packages/eight-sleep
  - packages/zwift-client
  - packages/trainerroad-client
  - packages/velohero-client

ignoredBuiltDependencies:
  - cpu-features
  - esbuild
  - protobufjs
  - ssh2
