import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    globals: true,
    testTimeout: 30_000,
    hookTimeout: 120_000,
    teardownTimeout: 60_000,
    fileParallelism: true,
    pool: "forks",
    include: ["src/**/*.test.ts", "packages/*/src/**/*.test.ts"],
    coverage: {
      provider: "v8",
      reporter: ["text", "json-summary"],
      include: ["src/**/*.ts", "packages/*/src/**/*.ts"],
      exclude: [
        "**/*.test.ts",
        "**/test-helpers.ts",
        "**/fixtures/**",
        "**/node_modules/**",
        "src/index.ts",
        "src/server.ts",
        "src/providers/types.ts",
        "src/auth/index.ts",
        "packages/server/src/types.ts",
        "src/db/schema.ts",
        "packages/server/src/index.ts",
        "packages/web/src/**",
        "packages/whoop-whoop/src/**",
        "packages/eight-sleep/src/**",
        "packages/zwift-client/src/**",
        "packages/trainerroad-client/src/**",
        "packages/velohero-client/src/**",
        "packages/garmin-connect/src/**",
        "src/providers/concept2.ts",
        "src/providers/coros.ts",
        "src/providers/cycling-analytics.ts",
        "src/providers/decathlon.ts",
        "src/providers/komoot.ts",
        "src/providers/mapmyfitness.ts",
        "src/providers/suunto.ts",
        "src/providers/ultrahuman.ts",
        "src/providers/wger.ts",
        "src/providers/xert.ts",
        "src/providers/trainerroad.ts",
        "src/providers/velohero.ts",
        "src/providers/zwift.ts",
        "src/providers/eight-sleep.ts",
        "src/jobs/worker.ts",
      ],
      thresholds: {
        lines: 91,
        functions: 95,
        branches: 81,
        statements: 91,
      },
    },
  },
  resolve: {
    alias: {
      "@": "./src",
    },
  },
});
