-- squawk-ignore-file prefer-bigint-over-int
CREATE TABLE IF NOT EXISTS fitness.food_entry_nutrition (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    food_entry_id uuid NOT NULL,
    calories integer,
    protein_g real,
    carbs_g real,
    fat_g real,
    saturated_fat_g real,
    polyunsaturated_fat_g real,
    monounsaturated_fat_g real,
    trans_fat_g real,
    cholesterol_mg real,
    sodium_mg real,
    potassium_mg real,
    fiber_g real,
    sugar_g real,
    vitamin_a_mcg real,
    vitamin_c_mg real,
    vitamin_d_mcg real,
    vitamin_e_mg real,
    vitamin_k_mcg real,
    vitamin_b1_mg real,
    vitamin_b2_mg real,
    vitamin_b3_mg real,
    vitamin_b5_mg real,
    vitamin_b6_mg real,
    vitamin_b7_mcg real,
    vitamin_b9_mcg real,
    vitamin_b12_mcg real,
    calcium_mg real,
    iron_mg real,
    magnesium_mg real,
    zinc_mg real,
    selenium_mcg real,
    copper_mg real,
    manganese_mg real,
    chromium_mcg real,
    iodine_mcg real,
    omega3_mg real,
    omega6_mg real,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT food_entry_nutrition_pkey PRIMARY KEY (id),
    CONSTRAINT food_entry_nutrition_food_entry_id_unique UNIQUE (food_entry_id),
    CONSTRAINT food_entry_nutrition_food_entry_id_fkey FOREIGN KEY (food_entry_id)
      REFERENCES fitness.food_entry(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS food_entry_nutrition_entry_idx
  ON fitness.food_entry_nutrition USING btree (food_entry_id);

CREATE TABLE IF NOT EXISTS fitness.supplement_nutrition (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    supplement_id uuid NOT NULL,
    calories integer,
    protein_g real,
    carbs_g real,
    fat_g real,
    saturated_fat_g real,
    polyunsaturated_fat_g real,
    monounsaturated_fat_g real,
    trans_fat_g real,
    cholesterol_mg real,
    sodium_mg real,
    potassium_mg real,
    fiber_g real,
    sugar_g real,
    vitamin_a_mcg real,
    vitamin_c_mg real,
    vitamin_d_mcg real,
    vitamin_e_mg real,
    vitamin_k_mcg real,
    vitamin_b1_mg real,
    vitamin_b2_mg real,
    vitamin_b3_mg real,
    vitamin_b5_mg real,
    vitamin_b6_mg real,
    vitamin_b7_mcg real,
    vitamin_b9_mcg real,
    vitamin_b12_mcg real,
    calcium_mg real,
    iron_mg real,
    magnesium_mg real,
    zinc_mg real,
    selenium_mcg real,
    copper_mg real,
    manganese_mg real,
    chromium_mcg real,
    iodine_mcg real,
    omega3_mg real,
    omega6_mg real,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT supplement_nutrition_pkey PRIMARY KEY (id),
    CONSTRAINT supplement_nutrition_supplement_id_unique UNIQUE (supplement_id),
    CONSTRAINT supplement_nutrition_supplement_id_fkey FOREIGN KEY (supplement_id)
      REFERENCES fitness.supplement(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS supplement_nutrition_supplement_idx
  ON fitness.supplement_nutrition USING btree (supplement_id);

INSERT INTO fitness.food_entry_nutrition (
    food_entry_id,
    calories,
    protein_g,
    carbs_g,
    fat_g,
    saturated_fat_g,
    polyunsaturated_fat_g,
    monounsaturated_fat_g,
    trans_fat_g,
    cholesterol_mg,
    sodium_mg,
    potassium_mg,
    fiber_g,
    sugar_g,
    vitamin_a_mcg,
    vitamin_c_mg,
    vitamin_d_mcg,
    vitamin_e_mg,
    vitamin_k_mcg,
    vitamin_b1_mg,
    vitamin_b2_mg,
    vitamin_b3_mg,
    vitamin_b5_mg,
    vitamin_b6_mg,
    vitamin_b7_mcg,
    vitamin_b9_mcg,
    vitamin_b12_mcg,
    calcium_mg,
    iron_mg,
    magnesium_mg,
    zinc_mg,
    selenium_mcg,
    copper_mg,
    manganese_mg,
    chromium_mcg,
    iodine_mcg,
    omega3_mg,
    omega6_mg,
    created_at,
    updated_at
)
SELECT
    fe.id,
    nd.calories,
    nd.protein_g,
    nd.carbs_g,
    nd.fat_g,
    nd.saturated_fat_g,
    nd.polyunsaturated_fat_g,
    nd.monounsaturated_fat_g,
    nd.trans_fat_g,
    nd.cholesterol_mg,
    nd.sodium_mg,
    nd.potassium_mg,
    nd.fiber_g,
    nd.sugar_g,
    nd.vitamin_a_mcg,
    nd.vitamin_c_mg,
    nd.vitamin_d_mcg,
    nd.vitamin_e_mg,
    nd.vitamin_k_mcg,
    nd.vitamin_b1_mg,
    nd.vitamin_b2_mg,
    nd.vitamin_b3_mg,
    nd.vitamin_b5_mg,
    nd.vitamin_b6_mg,
    nd.vitamin_b7_mcg,
    nd.vitamin_b9_mcg,
    nd.vitamin_b12_mcg,
    nd.calcium_mg,
    nd.iron_mg,
    nd.magnesium_mg,
    nd.zinc_mg,
    nd.selenium_mcg,
    nd.copper_mg,
    nd.manganese_mg,
    nd.chromium_mcg,
    nd.iodine_mcg,
    nd.omega3_mg,
    nd.omega6_mg,
    nd.created_at,
    nd.updated_at
FROM fitness.food_entry fe
JOIN fitness.nutrition_data nd ON nd.id = fe.nutrition_data_id
LEFT JOIN fitness.food_entry_nutrition fen ON fen.food_entry_id = fe.id
WHERE fe.nutrition_data_id IS NOT NULL
  AND fen.food_entry_id IS NULL;

INSERT INTO fitness.supplement_nutrition (
    supplement_id,
    calories,
    protein_g,
    carbs_g,
    fat_g,
    saturated_fat_g,
    polyunsaturated_fat_g,
    monounsaturated_fat_g,
    trans_fat_g,
    cholesterol_mg,
    sodium_mg,
    potassium_mg,
    fiber_g,
    sugar_g,
    vitamin_a_mcg,
    vitamin_c_mg,
    vitamin_d_mcg,
    vitamin_e_mg,
    vitamin_k_mcg,
    vitamin_b1_mg,
    vitamin_b2_mg,
    vitamin_b3_mg,
    vitamin_b5_mg,
    vitamin_b6_mg,
    vitamin_b7_mcg,
    vitamin_b9_mcg,
    vitamin_b12_mcg,
    calcium_mg,
    iron_mg,
    magnesium_mg,
    zinc_mg,
    selenium_mcg,
    copper_mg,
    manganese_mg,
    chromium_mcg,
    iodine_mcg,
    omega3_mg,
    omega6_mg,
    created_at,
    updated_at
)
SELECT
    s.id,
    nd.calories,
    nd.protein_g,
    nd.carbs_g,
    nd.fat_g,
    nd.saturated_fat_g,
    nd.polyunsaturated_fat_g,
    nd.monounsaturated_fat_g,
    nd.trans_fat_g,
    nd.cholesterol_mg,
    nd.sodium_mg,
    nd.potassium_mg,
    nd.fiber_g,
    nd.sugar_g,
    nd.vitamin_a_mcg,
    nd.vitamin_c_mg,
    nd.vitamin_d_mcg,
    nd.vitamin_e_mg,
    nd.vitamin_k_mcg,
    nd.vitamin_b1_mg,
    nd.vitamin_b2_mg,
    nd.vitamin_b3_mg,
    nd.vitamin_b5_mg,
    nd.vitamin_b6_mg,
    nd.vitamin_b7_mcg,
    nd.vitamin_b9_mcg,
    nd.vitamin_b12_mcg,
    nd.calcium_mg,
    nd.iron_mg,
    nd.magnesium_mg,
    nd.zinc_mg,
    nd.selenium_mcg,
    nd.copper_mg,
    nd.manganese_mg,
    nd.chromium_mcg,
    nd.iodine_mcg,
    nd.omega3_mg,
    nd.omega6_mg,
    nd.created_at,
    nd.updated_at
FROM fitness.supplement s
JOIN fitness.nutrition_data nd ON nd.id = s.nutrition_data_id
LEFT JOIN fitness.supplement_nutrition sn ON sn.supplement_id = s.id
WHERE s.nutrition_data_id IS NOT NULL
  AND sn.supplement_id IS NULL;

DROP VIEW IF EXISTS fitness.v_food_entry_with_nutrition;
DROP VIEW IF EXISTS fitness.v_supplement_with_nutrition;

ALTER TABLE fitness.food_entry DROP CONSTRAINT IF EXISTS food_entry_nutrition_data_id_fkey;
DROP INDEX CONCURRENTLY IF EXISTS fitness.food_entry_nutrition_data_idx;
ALTER TABLE fitness.food_entry DROP COLUMN IF EXISTS nutrition_data_id;

ALTER TABLE fitness.supplement DROP CONSTRAINT IF EXISTS supplement_nutrition_data_id_fkey;
DROP INDEX CONCURRENTLY IF EXISTS fitness.supplement_nutrition_data_idx;
ALTER TABLE fitness.supplement DROP COLUMN IF EXISTS nutrition_data_id;

CREATE VIEW fitness.v_food_entry_with_nutrition AS
SELECT
    fe.id,
    fe.provider_id,
    fe.user_id,
    fe.external_id,
    fe.date,
    fe.meal,
    fe.food_name,
    fe.food_description,
    fe.category,
    fe.provider_food_id,
    fe.provider_serving_id,
    fe.number_of_units,
    fe.logged_at,
    fe.barcode,
    fe.serving_unit,
    fe.serving_weight_grams,
    fen.id AS nutrition_data_id,
    fen.calories,
    fen.protein_g,
    fen.carbs_g,
    fen.fat_g,
    fen.saturated_fat_g,
    fen.polyunsaturated_fat_g,
    fen.monounsaturated_fat_g,
    fen.trans_fat_g,
    fen.cholesterol_mg,
    fen.sodium_mg,
    fen.potassium_mg,
    fen.fiber_g,
    fen.sugar_g,
    fen.vitamin_a_mcg,
    fen.vitamin_c_mg,
    fen.vitamin_d_mcg,
    fen.vitamin_e_mg,
    fen.vitamin_k_mcg,
    fen.vitamin_b1_mg,
    fen.vitamin_b2_mg,
    fen.vitamin_b3_mg,
    fen.vitamin_b5_mg,
    fen.vitamin_b6_mg,
    fen.vitamin_b7_mcg,
    fen.vitamin_b9_mcg,
    fen.vitamin_b12_mcg,
    fen.calcium_mg,
    fen.iron_mg,
    fen.magnesium_mg,
    fen.zinc_mg,
    fen.selenium_mcg,
    fen.copper_mg,
    fen.manganese_mg,
    fen.chromium_mcg,
    fen.iodine_mcg,
    fen.omega3_mg,
    fen.omega6_mg,
    fe.raw,
    fe.confirmed,
    fe.created_at
FROM fitness.food_entry fe
LEFT JOIN fitness.food_entry_nutrition fen ON fen.food_entry_id = fe.id;

CREATE VIEW fitness.v_supplement_with_nutrition AS
SELECT
    s.id,
    s.user_id,
    s.name,
    s.amount,
    s.unit,
    s.form,
    s.description,
    s.meal,
    s.sort_order,
    sn.id AS nutrition_data_id,
    sn.calories,
    sn.protein_g,
    sn.carbs_g,
    sn.fat_g,
    sn.saturated_fat_g,
    sn.polyunsaturated_fat_g,
    sn.monounsaturated_fat_g,
    sn.trans_fat_g,
    sn.cholesterol_mg,
    sn.sodium_mg,
    sn.potassium_mg,
    sn.fiber_g,
    sn.sugar_g,
    sn.vitamin_a_mcg,
    sn.vitamin_c_mg,
    sn.vitamin_d_mcg,
    sn.vitamin_e_mg,
    sn.vitamin_k_mcg,
    sn.vitamin_b1_mg,
    sn.vitamin_b2_mg,
    sn.vitamin_b3_mg,
    sn.vitamin_b5_mg,
    sn.vitamin_b6_mg,
    sn.vitamin_b7_mcg,
    sn.vitamin_b9_mcg,
    sn.vitamin_b12_mcg,
    sn.calcium_mg,
    sn.iron_mg,
    sn.magnesium_mg,
    sn.zinc_mg,
    sn.selenium_mcg,
    sn.copper_mg,
    sn.manganese_mg,
    sn.chromium_mcg,
    sn.iodine_mcg,
    sn.omega3_mg,
    sn.omega6_mg,
    s.created_at,
    s.updated_at
FROM fitness.supplement s
LEFT JOIN fitness.supplement_nutrition sn ON sn.supplement_id = s.id;
