version: 2

sources:
  - name: analytics
    schema: analytics
    tables:
      - name: v_activity
      - name: v_activity_members
  - name: postgres_fitness
    schema: postgres_fitness
    tables:
      - name: activity
      - name: metric_stream
        config:
          event_time: recorded_at
      - name: sensor_device_priority
      - name: sensor_provider_priority
      - name: sleep_session
      - name: user_profile
