export const SELECTED_RANGE_QUERY_REGISTRY = {
  behaviorImpact: ["behaviorImpact.impactSummary"],
  body: [
    "dailyMetrics.trends",
    "dailyMetrics.list",
    "dailyMetrics.hrvBaseline",
    "stress.scores",
    "bodyAnalytics.weightOverview",
    "insights.compute",
  ],
  correlation: ["correlation.computeV2"],
  cycling: [
    "power.powerCurve",
    "power.eftpTrend",
    "pmc.chart",
    "efficiency.aerobicEfficiency",
    "cyclingAdvanced.activityVariability",
    "cyclingAdvanced.verticalAscentRate",
  ],
  endurance: [
    "efficiency.polarizationTrend",
    "cyclingAdvanced.rampRate",
    "cyclingAdvanced.trainingMonotony",
  ],
  hiking: [
    "hiking.gradeAdjustedPace",
    "hiking.elevationProfile",
    "hiking.walkingBiomechanics",
    "hiking.activityComparison",
  ],
  journalLog: ["journal.entries"],
  journalTrends: ["journal.trends"],
  nutritionAnalytics: [
    "nutritionAnalytics.micronutrientAdequacyV2",
    "nutritionAnalytics.adaptiveTdee",
    "nutritionAnalytics.macroRatios",
  ],
  running: ["durationCurves.paceCurve", "running.paceTrendV2", "running.dynamicsV2"],
  recovery: [
    "recovery.hrvVariability",
    "dailyMetrics.hrvBaseline",
    "recovery.workloadRatio",
    "recovery.sleepAnalytics",
    "recovery.readinessScore",
  ],
  sleep: ["sleep.list", "insights.compute"],
  strength: [
    "strength.volumeOverTime",
    "strength.estimatedOneRepMax",
    "strength.muscleGroupVolume",
    "strength.progressiveOverload",
  ],
  trainingOverview: ["pmc.chart", "calendar.calendarData", "insights.compute"],
  trainingInsightsPanel: ["training.weeklyVolume", "training.hrZones"],
} as const;
