import { createSign } from "node:crypto";
import { readFile, stat } from "node:fs/promises";
import { join } from "node:path";
import * as Sentry from "@sentry/node";
import { Router } from "express";
import { z } from "zod";
import { logger as defaultLogger } from "../logger.ts";

interface Logger {
  info(message: string): void;
  error(message: string): void;
}

interface UpdatesStorage {
  downloadBuffer(key: string): Promise<Buffer>;
}

const manifestAssetSchema = z.object({
  hash: z.string(),
  key: z.string(),
  contentType: z.string(),
  fileExtension: z.string().optional(),
});

const manifestSchema = z.object({
  id: z.string(),
  createdAt: z.string(),
  runtimeVersion: z.string(),
  platform: z.string(),
  launchAsset: z.object({
    hash: z.string(),
    key: z.string(),
    contentType: z.string(),
  }),
  assets: z.array(manifestAssetSchema),
  metadata: z.record(z.unknown()).optional(),
  extra: z.record(z.unknown()).optional(),
});

type Manifest = z.infer<typeof manifestSchema>;

const releasePointerSchema = z.object({
  releaseId: z.string().min(1),
});

interface ManifestCache {
  releaseId?: string;
  manifest: Manifest | null;
  mtimeMs?: number;
  fetchedAtMs: number;
}

interface ReleasePointerCache {
  releaseId: string | null;
  fetchedAtMs: number;
}

export function createUpdatesRouter(deps: {
  updatesDir?: string;
  publicUrl: string;
  updatesStorage?: UpdatesStorage;
  updatesPrefix?: string;
  logger?: Logger;
  signingPrivateKey?: string;
}): Router {
  const router = Router();
  const logger = deps.logger ?? defaultLogger;
  const updatesPrefix = (deps.updatesPrefix ?? "mobile-ota").replace(/^\/+|\/+$/g, "");
  const releasePointerKey = `${updatesPrefix}/current-release.json`;
  let manifestCache: ManifestCache | null = null;
  let releasePointerCache: ReleasePointerCache | null = null;
  const objectStorageCacheTtlMs = 5_000;

  function buildReleaseStorageKey(releaseId: string, filePath: string): string {
    return `${updatesPrefix}/releases/${releaseId}/${filePath}`;
  }

  function isNotFoundError(error: unknown): boolean {
    if (!(error instanceof Error)) return false;
    const parsedError = z
      .object({
        name: z.string().optional(),
        code: z.string().optional(),
        Code: z.string().optional(),
        $metadata: z.object({ httpStatusCode: z.number().optional() }).optional(),
      })
      .safeParse(error);
    if (!parsedError.success) return false;
    const anyError = parsedError.data;
    return (
      anyError.code === "ENOENT" ||
      anyError.code === "NoSuchKey" ||
      anyError.Code === "NoSuchKey" ||
      anyError.name === "NoSuchKey" ||
      anyError.$metadata?.httpStatusCode === 404
    );
  }

  async function loadCurrentReleaseId(): Promise<string | null> {
    if (deps.updatesStorage) {
      if (
        releasePointerCache &&
        Date.now() - releasePointerCache.fetchedAtMs < objectStorageCacheTtlMs
      ) {
        return releasePointerCache.releaseId;
      }

      let pointerBuffer: Buffer;
      try {
        pointerBuffer = await deps.updatesStorage.downloadBuffer(releasePointerKey);
      } catch (error) {
        if (isNotFoundError(error)) {
          releasePointerCache = {
            releaseId: null,
            fetchedAtMs: Date.now(),
          };
          return null;
        }
        Sentry.captureException(error);
        logger.error(
          `[updates] Failed to read release pointer from object storage: ${String(error)}`,
        );
        releasePointerCache = {
          releaseId: null,
          fetchedAtMs: Date.now(),
        };
        return null;
      }

      let pointerJson: unknown;
      try {
        pointerJson = JSON.parse(pointerBuffer.toString("utf-8"));
      } catch (error) {
        Sentry.captureException(error);
        logger.error("[updates] Malformed JSON in current-release.json");
        releasePointerCache = {
          releaseId: null,
          fetchedAtMs: Date.now(),
        };
        return null;
      }

      const parsed = releasePointerSchema.safeParse(pointerJson);
      if (!parsed.success) {
        logger.error(`[updates] Invalid current-release.json: ${parsed.error.message}`);
        releasePointerCache = {
          releaseId: null,
          fetchedAtMs: Date.now(),
        };
        return null;
      }

      releasePointerCache = {
        releaseId: parsed.data.releaseId,
        fetchedAtMs: Date.now(),
      };
      return parsed.data.releaseId;
    }

    return "current";
  }

  async function loadManifest(releaseId: string): Promise<Manifest | null> {
    if (deps.updatesStorage) {
      if (
        manifestCache &&
        manifestCache.releaseId === releaseId &&
        Date.now() - manifestCache.fetchedAtMs < objectStorageCacheTtlMs
      ) {
        return manifestCache.manifest;
      }

      let manifestBuffer: Buffer;
      try {
        // We use 'expo-updates-manifest.json' as the standard filename generated by the new CI flow
        manifestBuffer = await deps.updatesStorage.downloadBuffer(
          buildReleaseStorageKey(releaseId, "expo-updates-manifest.json"),
        );
      } catch (error) {
        if (isNotFoundError(error)) {
          manifestCache = null;
          return null;
        }
        Sentry.captureException(error);
        logger.error(
          `[updates] Failed to read manifest from object storage for release ${releaseId}: ${String(error)}`,
        );
        manifestCache = null;
        return null;
      }

      let manifestJson: unknown;
      try {
        manifestJson = JSON.parse(manifestBuffer.toString("utf-8"));
      } catch (error) {
        Sentry.captureException(error);
        logger.error("[updates] Malformed JSON in expo-updates-manifest.json");
        manifestCache = null;
        return null;
      }

      const parsed = manifestSchema.safeParse(manifestJson);
      if (!parsed.success) {
        logger.error(`[updates] Invalid expo-updates-manifest.json: ${parsed.error.message}`);
        manifestCache = null;
        return null;
      }

      manifestCache = {
        releaseId,
        manifest: parsed.data,
        fetchedAtMs: Date.now(),
      };
      return parsed.data;
    }

    const updatesDir = deps.updatesDir;
    if (!updatesDir) {
      manifestCache = null;
      return null;
    }
    if (releaseId !== "current") {
      return null;
    }

    const manifestPath = join(updatesDir, "current", "expo-updates-manifest.json");
    let fileStat: Awaited<ReturnType<typeof stat>>;
    try {
      fileStat = await stat(manifestPath);
    } catch {
      manifestCache = null;
      return null;
    }

    if (manifestCache && manifestCache.mtimeMs === fileStat.mtimeMs) {
      return manifestCache.manifest;
    }

    let raw: string;
    try {
      raw = await readFile(manifestPath, "utf-8");
    } catch (error) {
      if (isNotFoundError(error)) {
        manifestCache = null;
        return null;
      }
      Sentry.captureException(error);
      logger.error(`[updates] Failed to read manifest from disk: ${String(error)}`);
      manifestCache = null;
      return null;
    }

    let json: unknown;
    try {
      json = JSON.parse(raw);
    } catch {
      logger.error("[updates] Malformed JSON in expo-updates-manifest.json");
      manifestCache = null;
      return null;
    }

    const parsed = manifestSchema.safeParse(json);

    if (!parsed.success) {
      logger.error(`[updates] Invalid manifest: ${parsed.error.message}`);
      manifestCache = null;
      return null;
    }

    manifestCache = {
      manifest: parsed.data,
      mtimeMs: fileStat.mtimeMs,
      fetchedAtMs: Date.now(),
    };
    return parsed.data;
  }

  async function loadFileFromStorage(
    relativePath: string,
    releaseId: string,
  ): Promise<Buffer | null> {
    if (deps.updatesStorage) {
      try {
        return await deps.updatesStorage.downloadBuffer(
          buildReleaseStorageKey(releaseId, relativePath),
        );
      } catch (error) {
        if (isNotFoundError(error)) return null;
        Sentry.captureException(error);
        logger.error(
          `[updates] Failed to read ${relativePath} from object storage for release ${releaseId}: ${String(error)}`,
        );
        return null;
      }
    }

    if (!deps.updatesDir) return null;
    if (releaseId !== "current") return null;
    const fullPath = join(deps.updatesDir, "current", relativePath);
    try {
      return await readFile(fullPath);
    } catch (error) {
      if (isNotFoundError(error)) return null;
      Sentry.captureException(error);
      logger.error(`[updates] Failed to read ${relativePath} from disk: ${String(error)}`);
      return null;
    }
  }

  function signManifest(manifestJson: string): string {
    if (!deps.signingPrivateKey) return "";
    const sign = createSign("RSA-SHA256");
    sign.update(manifestJson);
    sign.end();
    return sign.sign(deps.signingPrivateKey, "base64");
  }

  router.get("/manifest", async (_req, res) => {
    const protocolVersion = _req.headers["expo-protocol-version"];
    if (protocolVersion !== "1") {
      res.status(400).json({ error: "Missing or unsupported expo-protocol-version" });
      return;
    }

    const platform = _req.headers["expo-platform"];
    const runtimeVersion = _req.headers["expo-runtime-version"];

    const releaseId = await loadCurrentReleaseId();
    if (!releaseId) {
      res.set("expo-protocol-version", "1");
      res.status(204).end();
      return;
    }

    const manifest = await loadManifest(releaseId);

    if (!manifest) {
      res.set("expo-protocol-version", "1");
      res.status(204).end();
      return;
    }

    if (typeof runtimeVersion !== "string" || manifest.runtimeVersion !== runtimeVersion) {
      logger.info(
        `[updates] Runtime version mismatch: client=${String(runtimeVersion)} server=${manifest.runtimeVersion}`,
      );
      res.set("expo-protocol-version", "1");
      res.status(204).end();
      return;
    }

    if (typeof platform !== "string" || manifest.platform !== platform) {
      logger.info(
        `[updates] Platform mismatch: client=${String(platform)} server=${manifest.platform}`,
      );
      res.set("expo-protocol-version", "1");
      res.status(204).end();
      return;
    }

    const baseUrl = deps.publicUrl.replace(/\/$/, "");
    const encodedReleaseId = encodeURIComponent(releaseId);

    // Build the final manifest with absolute URLs
    const manifestResponse = {
      ...manifest,
      launchAsset: {
        ...manifest.launchAsset,
        url: `${baseUrl}/api/updates/releases/${encodedReleaseId}/bundles/${manifest.launchAsset.key}`,
      },
      assets: manifest.assets.map((asset) => ({
        ...asset,
        url: `${baseUrl}/api/updates/releases/${encodedReleaseId}/assets/${asset.key}`,
      })),
    };

    const manifestJson = JSON.stringify(manifestResponse);
    const signature = signManifest(manifestJson);

    const boundary = "expo-manifest-boundary";
    const bodyParts = [
      `--${boundary}\r\n`,
      'content-disposition: form-data; name="manifest"\r\n',
      "content-type: application/json\r\n",
      "\r\n",
      `${manifestJson}\r\n`,
      `--${boundary}--\r\n`,
    ];

    res.set("expo-protocol-version", "1");
    res.set("content-type", `multipart/mixed; boundary=${boundary}`);
    if (signature) {
      res.set("expo-signature", `keyid="main",alg="rsa-v1_5-sha256",sig="${signature}"`);
    }
    res.send(bodyParts.join(""));
  });

  async function serveAssetByReleaseId(
    req: import("express").Request,
    res: import("express").Response,
    releaseId: string,
  ) {
    const manifest = await loadManifest(releaseId);
    if (!manifest) {
      res.status(404).json({ error: "No update manifest found for release" });
      return;
    }

    const assetKey = req.params.key;
    const matchingAsset = manifest.assets.find((asset) => asset.key === assetKey);
    if (!matchingAsset) {
      res.status(404).json({ error: "Asset not found in manifest" });
      return;
    }

    const buffer = await loadFileFromStorage(`assets/${matchingAsset.key}`, releaseId);
    if (!buffer) {
      res.status(404).json({ error: "Asset file not found" });
      return;
    }

    res.set("content-type", matchingAsset.contentType);
    res.set("cache-control", "public, immutable, max-age=31536000");
    res.send(buffer);
  }

  async function serveBundleByReleaseId(
    req: import("express").Request,
    res: import("express").Response,
    releaseId: string,
  ) {
    const manifest = await loadManifest(releaseId);
    if (!manifest) {
      res.status(404).json({ error: "No update manifest found for release" });
      return;
    }

    const bundleKey = req.params.key;
    if (manifest.launchAsset.key !== bundleKey) {
      res.status(404).json({ error: "Bundle not found in manifest" });
      return;
    }

    const buffer = await loadFileFromStorage(`bundles/${manifest.launchAsset.key}`, releaseId);
    if (!buffer) {
      res.status(404).json({ error: "Bundle file not found" });
      return;
    }

    res.set("content-type", manifest.launchAsset.contentType);
    res.set("cache-control", "public, immutable, max-age=31536000");
    res.send(buffer);
  }

  router.get("/releases/:releaseId/assets/:key", async (req, res) => {
    await serveAssetByReleaseId(req, res, req.params.releaseId);
  });

  router.get("/releases/:releaseId/bundles/:key", async (req, res) => {
    await serveBundleByReleaseId(req, res, req.params.releaseId);
  });

  // Legacy aliases: keep serving from current release pointer for compatibility.
  router.get("/assets/:key", async (req, res) => {
    const releaseId = await loadCurrentReleaseId();
    if (!releaseId) {
      res.status(404).json({ error: "No current OTA release configured" });
      return;
    }
    await serveAssetByReleaseId(req, res, releaseId);
  });

  router.get("/bundles/:key", async (req, res) => {
    const releaseId = await loadCurrentReleaseId();
    if (!releaseId) {
      res.status(404).json({ error: "No current OTA release configured" });
      return;
    }
    await serveBundleByReleaseId(req, res, releaseId);
  });

  return router;
}
