/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as TrackingRouteImport } from './routes/tracking'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SleepRouteImport } from './routes/sleep'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PredictionsRouteImport } from './routes/predictions'
import { Route as NutritionRouteImport } from './routes/nutrition'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CorrelationRouteImport } from './routes/correlation'
import { Route as BodyRouteImport } from './routes/body'
import { Route as BehaviorImpactRouteImport } from './routes/behavior-impact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrainingIndexRouteImport } from './routes/training/index'
import { Route as ProvidersIndexRouteImport } from './routes/providers/index'
import { Route as NutritionIndexRouteImport } from './routes/nutrition/index'
import { Route as TrainingStrengthRouteImport } from './routes/training/strength'
import { Route as TrainingRunningRouteImport } from './routes/training/running'
import { Route as TrainingRecoveryRouteImport } from './routes/training/recovery'
import { Route as TrainingHikingRouteImport } from './routes/training/hiking'
import { Route as TrainingEnduranceRouteImport } from './routes/training/endurance'
import { Route as TrainingCyclingRouteImport } from './routes/training/cycling'
import { Route as ProvidersIdRouteImport } from './routes/providers/$id'
import { Route as NutritionSupplementsRouteImport } from './routes/nutrition/supplements'
import { Route as NutritionAnalyticsRouteImport } from './routes/nutrition/analytics'
import { Route as ActivityIdRouteImport } from './routes/activity.$id'

const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingRoute = TrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SleepRoute = SleepRouteImport.update({
  id: '/sleep',
  path: '/sleep',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionsRoute = PredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionRoute = NutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CorrelationRoute = CorrelationRouteImport.update({
  id: '/correlation',
  path: '/correlation',
  getParentRoute: () => rootRouteImport,
} as any)
const BodyRoute = BodyRouteImport.update({
  id: '/body',
  path: '/body',
  getParentRoute: () => rootRouteImport,
} as any)
const BehaviorImpactRoute = BehaviorImpactRouteImport.update({
  id: '/behavior-impact',
  path: '/behavior-impact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingIndexRoute = TrainingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TrainingRoute,
} as any)
const ProvidersIndexRoute = ProvidersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProvidersRoute,
} as any)
const NutritionIndexRoute = NutritionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NutritionRoute,
} as any)
const TrainingStrengthRoute = TrainingStrengthRouteImport.update({
  id: '/strength',
  path: '/strength',
  getParentRoute: () => TrainingRoute,
} as any)
const TrainingRunningRoute = TrainingRunningRouteImport.update({
  id: '/running',
  path: '/running',
  getParentRoute: () => TrainingRoute,
} as any)
const TrainingRecoveryRoute = TrainingRecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => TrainingRoute,
} as any)
const TrainingHikingRoute = TrainingHikingRouteImport.update({
  id: '/hiking',
  path: '/hiking',
  getParentRoute: () => TrainingRoute,
} as any)
const TrainingEnduranceRoute = TrainingEnduranceRouteImport.update({
  id: '/endurance',
  path: '/endurance',
  getParentRoute: () => TrainingRoute,
} as any)
const TrainingCyclingRoute = TrainingCyclingRouteImport.update({
  id: '/cycling',
  path: '/cycling',
  getParentRoute: () => TrainingRoute,
} as any)
const ProvidersIdRoute = ProvidersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProvidersRoute,
} as any)
const NutritionSupplementsRoute = NutritionSupplementsRouteImport.update({
  id: '/supplements',
  path: '/supplements',
  getParentRoute: () => NutritionRoute,
} as any)
const NutritionAnalyticsRoute = NutritionAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => NutritionRoute,
} as any)
const ActivityIdRoute = ActivityIdRouteImport.update({
  id: '/activity/$id',
  path: '/activity/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/behavior-impact': typeof BehaviorImpactRoute
  '/body': typeof BodyRoute
  '/correlation': typeof CorrelationRoute
  '/dashboard': typeof DashboardRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/nutrition': typeof NutritionRouteWithChildren
  '/predictions': typeof PredictionsRoute
  '/privacy': typeof PrivacyRoute
  '/providers': typeof ProvidersRouteWithChildren
  '/settings': typeof SettingsRoute
  '/sleep': typeof SleepRoute
  '/terms': typeof TermsRoute
  '/tracking': typeof TrackingRoute
  '/training': typeof TrainingRouteWithChildren
  '/activity/$id': typeof ActivityIdRoute
  '/nutrition/analytics': typeof NutritionAnalyticsRoute
  '/nutrition/supplements': typeof NutritionSupplementsRoute
  '/providers/$id': typeof ProvidersIdRoute
  '/training/cycling': typeof TrainingCyclingRoute
  '/training/endurance': typeof TrainingEnduranceRoute
  '/training/hiking': typeof TrainingHikingRoute
  '/training/recovery': typeof TrainingRecoveryRoute
  '/training/running': typeof TrainingRunningRoute
  '/training/strength': typeof TrainingStrengthRoute
  '/nutrition/': typeof NutritionIndexRoute
  '/providers/': typeof ProvidersIndexRoute
  '/training/': typeof TrainingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/behavior-impact': typeof BehaviorImpactRoute
  '/body': typeof BodyRoute
  '/correlation': typeof CorrelationRoute
  '/dashboard': typeof DashboardRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/predictions': typeof PredictionsRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/sleep': typeof SleepRoute
  '/terms': typeof TermsRoute
  '/tracking': typeof TrackingRoute
  '/activity/$id': typeof ActivityIdRoute
  '/nutrition/analytics': typeof NutritionAnalyticsRoute
  '/nutrition/supplements': typeof NutritionSupplementsRoute
  '/providers/$id': typeof ProvidersIdRoute
  '/training/cycling': typeof TrainingCyclingRoute
  '/training/endurance': typeof TrainingEnduranceRoute
  '/training/hiking': typeof TrainingHikingRoute
  '/training/recovery': typeof TrainingRecoveryRoute
  '/training/running': typeof TrainingRunningRoute
  '/training/strength': typeof TrainingStrengthRoute
  '/nutrition': typeof NutritionIndexRoute
  '/providers': typeof ProvidersIndexRoute
  '/training': typeof TrainingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/behavior-impact': typeof BehaviorImpactRoute
  '/body': typeof BodyRoute
  '/correlation': typeof CorrelationRoute
  '/dashboard': typeof DashboardRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/nutrition': typeof NutritionRouteWithChildren
  '/predictions': typeof PredictionsRoute
  '/privacy': typeof PrivacyRoute
  '/providers': typeof ProvidersRouteWithChildren
  '/settings': typeof SettingsRoute
  '/sleep': typeof SleepRoute
  '/terms': typeof TermsRoute
  '/tracking': typeof TrackingRoute
  '/training': typeof TrainingRouteWithChildren
  '/activity/$id': typeof ActivityIdRoute
  '/nutrition/analytics': typeof NutritionAnalyticsRoute
  '/nutrition/supplements': typeof NutritionSupplementsRoute
  '/providers/$id': typeof ProvidersIdRoute
  '/training/cycling': typeof TrainingCyclingRoute
  '/training/endurance': typeof TrainingEnduranceRoute
  '/training/hiking': typeof TrainingHikingRoute
  '/training/recovery': typeof TrainingRecoveryRoute
  '/training/running': typeof TrainingRunningRoute
  '/training/strength': typeof TrainingStrengthRoute
  '/nutrition/': typeof NutritionIndexRoute
  '/providers/': typeof ProvidersIndexRoute
  '/training/': typeof TrainingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/behavior-impact'
    | '/body'
    | '/correlation'
    | '/dashboard'
    | '/insights'
    | '/login'
    | '/nutrition'
    | '/predictions'
    | '/privacy'
    | '/providers'
    | '/settings'
    | '/sleep'
    | '/terms'
    | '/tracking'
    | '/training'
    | '/activity/$id'
    | '/nutrition/analytics'
    | '/nutrition/supplements'
    | '/providers/$id'
    | '/training/cycling'
    | '/training/endurance'
    | '/training/hiking'
    | '/training/recovery'
    | '/training/running'
    | '/training/strength'
    | '/nutrition/'
    | '/providers/'
    | '/training/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/behavior-impact'
    | '/body'
    | '/correlation'
    | '/dashboard'
    | '/insights'
    | '/login'
    | '/predictions'
    | '/privacy'
    | '/settings'
    | '/sleep'
    | '/terms'
    | '/tracking'
    | '/activity/$id'
    | '/nutrition/analytics'
    | '/nutrition/supplements'
    | '/providers/$id'
    | '/training/cycling'
    | '/training/endurance'
    | '/training/hiking'
    | '/training/recovery'
    | '/training/running'
    | '/training/strength'
    | '/nutrition'
    | '/providers'
    | '/training'
  id:
    | '__root__'
    | '/'
    | '/behavior-impact'
    | '/body'
    | '/correlation'
    | '/dashboard'
    | '/insights'
    | '/login'
    | '/nutrition'
    | '/predictions'
    | '/privacy'
    | '/providers'
    | '/settings'
    | '/sleep'
    | '/terms'
    | '/tracking'
    | '/training'
    | '/activity/$id'
    | '/nutrition/analytics'
    | '/nutrition/supplements'
    | '/providers/$id'
    | '/training/cycling'
    | '/training/endurance'
    | '/training/hiking'
    | '/training/recovery'
    | '/training/running'
    | '/training/strength'
    | '/nutrition/'
    | '/providers/'
    | '/training/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BehaviorImpactRoute: typeof BehaviorImpactRoute
  BodyRoute: typeof BodyRoute
  CorrelationRoute: typeof CorrelationRoute
  DashboardRoute: typeof DashboardRoute
  InsightsRoute: typeof InsightsRoute
  LoginRoute: typeof LoginRoute
  NutritionRoute: typeof NutritionRouteWithChildren
  PredictionsRoute: typeof PredictionsRoute
  PrivacyRoute: typeof PrivacyRoute
  ProvidersRoute: typeof ProvidersRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SleepRoute: typeof SleepRoute
  TermsRoute: typeof TermsRoute
  TrackingRoute: typeof TrackingRoute
  TrainingRoute: typeof TrainingRouteWithChildren
  ActivityIdRoute: typeof ActivityIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking': {
      id: '/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof TrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sleep': {
      id: '/sleep'
      path: '/sleep'
      fullPath: '/sleep'
      preLoaderRoute: typeof SleepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictions': {
      id: '/predictions'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof PredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition': {
      id: '/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof NutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/correlation': {
      id: '/correlation'
      path: '/correlation'
      fullPath: '/correlation'
      preLoaderRoute: typeof CorrelationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/body': {
      id: '/body'
      path: '/body'
      fullPath: '/body'
      preLoaderRoute: typeof BodyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/behavior-impact': {
      id: '/behavior-impact'
      path: '/behavior-impact'
      fullPath: '/behavior-impact'
      preLoaderRoute: typeof BehaviorImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/': {
      id: '/training/'
      path: '/'
      fullPath: '/training/'
      preLoaderRoute: typeof TrainingIndexRouteImport
      parentRoute: typeof TrainingRoute
    }
    '/providers/': {
      id: '/providers/'
      path: '/'
      fullPath: '/providers/'
      preLoaderRoute: typeof ProvidersIndexRouteImport
      parentRoute: typeof ProvidersRoute
    }
    '/nutrition/': {
      id: '/nutrition/'
      path: '/'
      fullPath: '/nutrition/'
      preLoaderRoute: typeof NutritionIndexRouteImport
      parentRoute: typeof NutritionRoute
    }
    '/training/strength': {
      id: '/training/strength'
      path: '/strength'
      fullPath: '/training/strength'
      preLoaderRoute: typeof TrainingStrengthRouteImport
      parentRoute: typeof TrainingRoute
    }
    '/training/running': {
      id: '/training/running'
      path: '/running'
      fullPath: '/training/running'
      preLoaderRoute: typeof TrainingRunningRouteImport
      parentRoute: typeof TrainingRoute
    }
    '/training/recovery': {
      id: '/training/recovery'
      path: '/recovery'
      fullPath: '/training/recovery'
      preLoaderRoute: typeof TrainingRecoveryRouteImport
      parentRoute: typeof TrainingRoute
    }
    '/training/hiking': {
      id: '/training/hiking'
      path: '/hiking'
      fullPath: '/training/hiking'
      preLoaderRoute: typeof TrainingHikingRouteImport
      parentRoute: typeof TrainingRoute
    }
    '/training/endurance': {
      id: '/training/endurance'
      path: '/endurance'
      fullPath: '/training/endurance'
      preLoaderRoute: typeof TrainingEnduranceRouteImport
      parentRoute: typeof TrainingRoute
    }
    '/training/cycling': {
      id: '/training/cycling'
      path: '/cycling'
      fullPath: '/training/cycling'
      preLoaderRoute: typeof TrainingCyclingRouteImport
      parentRoute: typeof TrainingRoute
    }
    '/providers/$id': {
      id: '/providers/$id'
      path: '/$id'
      fullPath: '/providers/$id'
      preLoaderRoute: typeof ProvidersIdRouteImport
      parentRoute: typeof ProvidersRoute
    }
    '/nutrition/supplements': {
      id: '/nutrition/supplements'
      path: '/supplements'
      fullPath: '/nutrition/supplements'
      preLoaderRoute: typeof NutritionSupplementsRouteImport
      parentRoute: typeof NutritionRoute
    }
    '/nutrition/analytics': {
      id: '/nutrition/analytics'
      path: '/analytics'
      fullPath: '/nutrition/analytics'
      preLoaderRoute: typeof NutritionAnalyticsRouteImport
      parentRoute: typeof NutritionRoute
    }
    '/activity/$id': {
      id: '/activity/$id'
      path: '/activity/$id'
      fullPath: '/activity/$id'
      preLoaderRoute: typeof ActivityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface NutritionRouteChildren {
  NutritionAnalyticsRoute: typeof NutritionAnalyticsRoute
  NutritionSupplementsRoute: typeof NutritionSupplementsRoute
  NutritionIndexRoute: typeof NutritionIndexRoute
}

const NutritionRouteChildren: NutritionRouteChildren = {
  NutritionAnalyticsRoute: NutritionAnalyticsRoute,
  NutritionSupplementsRoute: NutritionSupplementsRoute,
  NutritionIndexRoute: NutritionIndexRoute,
}

const NutritionRouteWithChildren = NutritionRoute._addFileChildren(
  NutritionRouteChildren,
)

interface ProvidersRouteChildren {
  ProvidersIdRoute: typeof ProvidersIdRoute
  ProvidersIndexRoute: typeof ProvidersIndexRoute
}

const ProvidersRouteChildren: ProvidersRouteChildren = {
  ProvidersIdRoute: ProvidersIdRoute,
  ProvidersIndexRoute: ProvidersIndexRoute,
}

const ProvidersRouteWithChildren = ProvidersRoute._addFileChildren(
  ProvidersRouteChildren,
)

interface TrainingRouteChildren {
  TrainingCyclingRoute: typeof TrainingCyclingRoute
  TrainingEnduranceRoute: typeof TrainingEnduranceRoute
  TrainingHikingRoute: typeof TrainingHikingRoute
  TrainingRecoveryRoute: typeof TrainingRecoveryRoute
  TrainingRunningRoute: typeof TrainingRunningRoute
  TrainingStrengthRoute: typeof TrainingStrengthRoute
  TrainingIndexRoute: typeof TrainingIndexRoute
}

const TrainingRouteChildren: TrainingRouteChildren = {
  TrainingCyclingRoute: TrainingCyclingRoute,
  TrainingEnduranceRoute: TrainingEnduranceRoute,
  TrainingHikingRoute: TrainingHikingRoute,
  TrainingRecoveryRoute: TrainingRecoveryRoute,
  TrainingRunningRoute: TrainingRunningRoute,
  TrainingStrengthRoute: TrainingStrengthRoute,
  TrainingIndexRoute: TrainingIndexRoute,
}

const TrainingRouteWithChildren = TrainingRoute._addFileChildren(
  TrainingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BehaviorImpactRoute: BehaviorImpactRoute,
  BodyRoute: BodyRoute,
  CorrelationRoute: CorrelationRoute,
  DashboardRoute: DashboardRoute,
  InsightsRoute: InsightsRoute,
  LoginRoute: LoginRoute,
  NutritionRoute: NutritionRouteWithChildren,
  PredictionsRoute: PredictionsRoute,
  PrivacyRoute: PrivacyRoute,
  ProvidersRoute: ProvidersRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SleepRoute: SleepRoute,
  TermsRoute: TermsRoute,
  TrackingRoute: TrackingRoute,
  TrainingRoute: TrainingRouteWithChildren,
  ActivityIdRoute: ActivityIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
