/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as TrackingRouteImport } from './routes/tracking'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as PredictionsRouteImport } from './routes/predictions'
import { Route as NutritionAnalyticsRouteImport } from './routes/nutrition-analytics'
import { Route as NutritionRouteImport } from './routes/nutrition'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrainingIndexRouteImport } from './routes/training/index'
import { Route as TrainingStrengthRouteImport } from './routes/training/strength'
import { Route as TrainingRecoveryRouteImport } from './routes/training/recovery'
import { Route as TrainingHikingRouteImport } from './routes/training/hiking'
import { Route as TrainingEnduranceRouteImport } from './routes/training/endurance'

const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackingRoute = TrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionsRoute = PredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionAnalyticsRoute = NutritionAnalyticsRouteImport.update({
  id: '/nutrition-analytics',
  path: '/nutrition-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionRoute = NutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingIndexRoute = TrainingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TrainingRoute,
} as any)
const TrainingStrengthRoute = TrainingStrengthRouteImport.update({
  id: '/strength',
  path: '/strength',
  getParentRoute: () => TrainingRoute,
} as any)
const TrainingRecoveryRoute = TrainingRecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => TrainingRoute,
} as any)
const TrainingHikingRoute = TrainingHikingRouteImport.update({
  id: '/hiking',
  path: '/hiking',
  getParentRoute: () => TrainingRoute,
} as any)
const TrainingEnduranceRoute = TrainingEnduranceRouteImport.update({
  id: '/endurance',
  path: '/endurance',
  getParentRoute: () => TrainingRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/nutrition': typeof NutritionRoute
  '/nutrition-analytics': typeof NutritionAnalyticsRoute
  '/predictions': typeof PredictionsRoute
  '/providers': typeof ProvidersRoute
  '/settings': typeof SettingsRoute
  '/tracking': typeof TrackingRoute
  '/training': typeof TrainingRouteWithChildren
  '/training/endurance': typeof TrainingEnduranceRoute
  '/training/hiking': typeof TrainingHikingRoute
  '/training/recovery': typeof TrainingRecoveryRoute
  '/training/strength': typeof TrainingStrengthRoute
  '/training/': typeof TrainingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/nutrition': typeof NutritionRoute
  '/nutrition-analytics': typeof NutritionAnalyticsRoute
  '/predictions': typeof PredictionsRoute
  '/providers': typeof ProvidersRoute
  '/settings': typeof SettingsRoute
  '/tracking': typeof TrackingRoute
  '/training/endurance': typeof TrainingEnduranceRoute
  '/training/hiking': typeof TrainingHikingRoute
  '/training/recovery': typeof TrainingRecoveryRoute
  '/training/strength': typeof TrainingStrengthRoute
  '/training': typeof TrainingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/insights': typeof InsightsRoute
  '/login': typeof LoginRoute
  '/nutrition': typeof NutritionRoute
  '/nutrition-analytics': typeof NutritionAnalyticsRoute
  '/predictions': typeof PredictionsRoute
  '/providers': typeof ProvidersRoute
  '/settings': typeof SettingsRoute
  '/tracking': typeof TrackingRoute
  '/training': typeof TrainingRouteWithChildren
  '/training/endurance': typeof TrainingEnduranceRoute
  '/training/hiking': typeof TrainingHikingRoute
  '/training/recovery': typeof TrainingRecoveryRoute
  '/training/strength': typeof TrainingStrengthRoute
  '/training/': typeof TrainingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/insights'
    | '/login'
    | '/nutrition'
    | '/nutrition-analytics'
    | '/predictions'
    | '/providers'
    | '/settings'
    | '/tracking'
    | '/training'
    | '/training/endurance'
    | '/training/hiking'
    | '/training/recovery'
    | '/training/strength'
    | '/training/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/insights'
    | '/login'
    | '/nutrition'
    | '/nutrition-analytics'
    | '/predictions'
    | '/providers'
    | '/settings'
    | '/tracking'
    | '/training/endurance'
    | '/training/hiking'
    | '/training/recovery'
    | '/training/strength'
    | '/training'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/insights'
    | '/login'
    | '/nutrition'
    | '/nutrition-analytics'
    | '/predictions'
    | '/providers'
    | '/settings'
    | '/tracking'
    | '/training'
    | '/training/endurance'
    | '/training/hiking'
    | '/training/recovery'
    | '/training/strength'
    | '/training/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  InsightsRoute: typeof InsightsRoute
  LoginRoute: typeof LoginRoute
  NutritionRoute: typeof NutritionRoute
  NutritionAnalyticsRoute: typeof NutritionAnalyticsRoute
  PredictionsRoute: typeof PredictionsRoute
  ProvidersRoute: typeof ProvidersRoute
  SettingsRoute: typeof SettingsRoute
  TrackingRoute: typeof TrackingRoute
  TrainingRoute: typeof TrainingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracking': {
      id: '/tracking'
      path: '/tracking'
      fullPath: '/tracking'
      preLoaderRoute: typeof TrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictions': {
      id: '/predictions'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof PredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition-analytics': {
      id: '/nutrition-analytics'
      path: '/nutrition-analytics'
      fullPath: '/nutrition-analytics'
      preLoaderRoute: typeof NutritionAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition': {
      id: '/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof NutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/': {
      id: '/training/'
      path: '/'
      fullPath: '/training/'
      preLoaderRoute: typeof TrainingIndexRouteImport
      parentRoute: typeof TrainingRoute
    }
    '/training/strength': {
      id: '/training/strength'
      path: '/strength'
      fullPath: '/training/strength'
      preLoaderRoute: typeof TrainingStrengthRouteImport
      parentRoute: typeof TrainingRoute
    }
    '/training/recovery': {
      id: '/training/recovery'
      path: '/recovery'
      fullPath: '/training/recovery'
      preLoaderRoute: typeof TrainingRecoveryRouteImport
      parentRoute: typeof TrainingRoute
    }
    '/training/hiking': {
      id: '/training/hiking'
      path: '/hiking'
      fullPath: '/training/hiking'
      preLoaderRoute: typeof TrainingHikingRouteImport
      parentRoute: typeof TrainingRoute
    }
    '/training/endurance': {
      id: '/training/endurance'
      path: '/endurance'
      fullPath: '/training/endurance'
      preLoaderRoute: typeof TrainingEnduranceRouteImport
      parentRoute: typeof TrainingRoute
    }
  }
}

interface TrainingRouteChildren {
  TrainingEnduranceRoute: typeof TrainingEnduranceRoute
  TrainingHikingRoute: typeof TrainingHikingRoute
  TrainingRecoveryRoute: typeof TrainingRecoveryRoute
  TrainingStrengthRoute: typeof TrainingStrengthRoute
  TrainingIndexRoute: typeof TrainingIndexRoute
}

const TrainingRouteChildren: TrainingRouteChildren = {
  TrainingEnduranceRoute: TrainingEnduranceRoute,
  TrainingHikingRoute: TrainingHikingRoute,
  TrainingRecoveryRoute: TrainingRecoveryRoute,
  TrainingStrengthRoute: TrainingStrengthRoute,
  TrainingIndexRoute: TrainingIndexRoute,
}

const TrainingRouteWithChildren = TrainingRoute._addFileChildren(
  TrainingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  InsightsRoute: InsightsRoute,
  LoginRoute: LoginRoute,
  NutritionRoute: NutritionRoute,
  NutritionAnalyticsRoute: NutritionAnalyticsRoute,
  PredictionsRoute: PredictionsRoute,
  ProvidersRoute: ProvidersRoute,
  SettingsRoute: SettingsRoute,
  TrackingRoute: TrackingRoute,
  TrainingRoute: TrainingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
