import { buildActivitySensorSummaryRowsTableSql } from "../../../../src/db/clickhouse-activity-sensor-summary.ts";

export interface IsolatedClickHouseDatabases {
  analytics: string;
  ingest: string;
  postgresFitness: string;
}

export function rewriteClickHouseDatabaseNames(
  query: string,
  databases: IsolatedClickHouseDatabases,
): string {
  return query
    .replace(/\bpostgres_fitness\b/g, databases.postgresFitness)
    .replace(/\bingest\b/g, databases.ingest)
    .replace(/\banalytics\b/g, databases.analytics);
}

export const CLICKHOUSE_TEST_VIEW_REGEX =
  /^CREATE (?:MATERIALIZED )?VIEW IF NOT EXISTS ([A-Za-z0-9_]+\.[A-Za-z0-9_]+)(?:\n[\s\S]*?)?\nAS\n?([\s\S]*)$/;
export const clickHouseMigrationAnalyticsViewNames = [
  "analytics.v_activity",
  "analytics.v_activity_members",
  "analytics.v_sleep",
  "analytics.v_daily_metrics",
  "analytics.provider_stats",
  "analytics.deduped_sensor",
  "analytics.resting_heart_rate_sleep_window",
  "analytics.daily_recovery_inputs",
  "analytics.daily_recovery",
  "analytics.deduped_location",
  "analytics.daily_endurance_load",
  "analytics.activity_summary",
  "analytics.hiking_activity",
  "analytics.daily_activity_load",
  "analytics.weekly_endurance_ramp_rate",
  "analytics.weekly_training_monotony",
  "analytics.daily_strain",
  "analytics.daily_body_measurement",
  "analytics.healthspan_activity_zone_minutes",
  "analytics.weekly_healthspan",
  "analytics.activity_trend_daily",
] as const;
export const analyticsBuildOrder = [
  "analytics.v_activity",
  "analytics.v_activity_members",
  "analytics.v_sleep",
  "analytics.v_body_measurement",
  "analytics.v_daily_metrics",
  "analytics.provider_stats",
  "analytics.deduped_activities",
  "analytics.resting_heart_rate_sleep_window",
  "analytics.daily_sleep",
  "analytics.daily_recovery_inputs",
  "analytics.daily_recovery",
  "analytics.deduped_location",
  "analytics.activity_location_sample",
  "analytics.activity_sensor_sample",
  "analytics.activity_location_summary_rows",
  "analytics.activity_sensor_summary_rows",
  "analytics.activity_stream_points",
  "analytics.activity_heart_rate_zones",
  "analytics.activity_summary",
  "analytics.daily_endurance_load",
  "analytics.hiking_activity",
  "analytics.daily_activity_load",
  "analytics.weekly_endurance_ramp_rate",
  "analytics.weekly_training_monotony",
  "analytics.daily_strain",
  "analytics.daily_body_measurement",
  "analytics.healthspan_activity_zone_minutes",
  "analytics.weekly_healthspan",
  "analytics.activity_trend_daily",
] as const;

export function buildTestAnalyticsTableStatement(viewName: string): string {
  const columnDefinitionsByViewName: Record<string, string> = {
    v_activity: `id UUID,
provider_id String,
user_id UUID,
primary_activity_id UUID,
canonical_type String,
provider_type String,
modality Nullable(String),
started_at DateTime64(6, 'UTC'),
ended_at Nullable(DateTime64(6, 'UTC')),
source_name Nullable(String),
name Nullable(String),
notes Nullable(String),
timezone Nullable(String),
start_utc_offset_minutes Nullable(Int16),
end_utc_offset_minutes Nullable(Int16),
local_time_source String,
raw Nullable(String),
source_providers Array(String),
source_external_ids Array(Map(String, Nullable(String))),
absent_source_external_ids Array(Map(String, Nullable(String))),
member_activity_ids Array(UUID)`,
    v_activity_members: `activity_id UUID,
user_id UUID,
started_at DateTime64(6, 'UTC'),
ended_at Nullable(DateTime64(6, 'UTC')),
member_activity_id UUID`,
    v_sleep: `id UUID,
provider_id String,
user_id UUID,
started_at DateTime64(6, 'UTC'),
ended_at Nullable(DateTime64(6, 'UTC')),
duration_minutes Nullable(Int32),
deep_minutes Nullable(Int32),
rem_minutes Nullable(Int32),
light_minutes Nullable(Int32),
awake_minutes Nullable(Int32),
staging_available Bool,
efficiency_pct Nullable(Float64),
sleep_type Nullable(String),
is_nap Nullable(Bool),
source_name Nullable(String),
timezone Nullable(String),
start_utc_offset_minutes Nullable(Int16),
end_utc_offset_minutes Nullable(Int16),
local_time_source String,
source_providers Array(String)`,
    resting_heart_rate_sleep_window: `sleep_id UUID,
user_id UUID,
started_at Nullable(DateTime64(6, 'UTC')),
ended_at Nullable(DateTime64(6, 'UTC')),
duration_seconds Nullable(Int64),
sample_count UInt64,
resting_hr Nullable(Int32),
refresh_version UInt64,
is_deleted UInt8,
refreshed_at DateTime64(9)`,
    daily_sleep: `user_id UUID,
date Date,
provider_id String,
source_name Nullable(String),
source_providers Array(String),
selected_session_id Nullable(UUID),
overlapping_sessions Array(Tuple(
  session_id UUID,
  provider_id String,
  source_name Nullable(String),
  source_providers Array(String),
  timezone Nullable(String),
  start_utc_offset_minutes Nullable(Int16),
  end_utc_offset_minutes Nullable(Int16),
  local_time_source String,
  started_at DateTime64(6, 'UTC'),
  ended_at Nullable(DateTime64(6, 'UTC')),
  duration_minutes Nullable(Int32)
)),
timezone Nullable(String),
start_utc_offset_minutes Nullable(Int16),
end_utc_offset_minutes Nullable(Int16),
local_time_source String,
started_at DateTime64(6, 'UTC'),
ended_at Nullable(DateTime64(6, 'UTC')),
duration_minutes Nullable(Int32),
deep_minutes Nullable(Int32),
rem_minutes Nullable(Int32),
light_minutes Nullable(Int32),
awake_minutes Nullable(Int32),
efficiency_pct Nullable(Float64),
staging_available Bool,
refresh_version UInt64,
is_deleted UInt8 DEFAULT 0,
refreshed_at DateTime64(9)`,
    daily_recovery_inputs: `user_id UUID,
date Date,
hrv Nullable(Float32),
resting_hr Nullable(Float64),
respiratory_rate Nullable(Float32),
efficiency_pct Nullable(Float64),
hrv_mean_30d Nullable(Float64),
hrv_sd_30d Nullable(Float64),
hrv_baseline_sample_count UInt16,
hrv_baseline_coverage Float64,
hrv_mean_7d Nullable(Float64),
hrv_mean_previous_28d Nullable(Float64),
rhr_mean_30d Nullable(Float64),
rhr_sd_30d Nullable(Float64),
rhr_baseline_sample_count UInt16,
rhr_baseline_coverage Float64,
rhr_mean_7d Nullable(Float64),
rhr_mean_previous_28d Nullable(Float64),
rr_mean_30d Nullable(Float64),
rr_sd_30d Nullable(Float64),
rr_baseline_sample_count UInt16,
rr_baseline_coverage Float64,
rr_mean_7d Nullable(Float64),
rr_mean_previous_28d Nullable(Float64),
efficiency_mean_30d Nullable(Float64),
efficiency_sd_30d Nullable(Float64),
efficiency_baseline_sample_count UInt16,
efficiency_baseline_coverage Float64,
efficiency_mean_7d Nullable(Float64),
efficiency_mean_previous_28d Nullable(Float64),
hrv_mean_60d Nullable(Float64),
hrv_sd_60d Nullable(Float64),
rhr_mean_60d Nullable(Float64),
rhr_sd_60d Nullable(Float64),
is_deleted UInt8 DEFAULT 0,
refresh_version UInt64,
refreshed_at DateTime64(9)`,
    daily_recovery: `user_id UUID,
date Date,
hrv Nullable(Float64),
resting_hr Nullable(Float64),
respiratory_rate Nullable(Float64),
efficiency_pct Nullable(Float64),
hrv_mean_30d Nullable(Float64),
hrv_sd_30d Nullable(Float64),
hrv_z_score Nullable(Float64),
hrv_baseline_sample_count UInt16,
hrv_baseline_coverage Float64,
hrv_mean_7d Nullable(Float64),
hrv_mean_previous_28d Nullable(Float64),
rhr_mean_30d Nullable(Float64),
rhr_sd_30d Nullable(Float64),
resting_hr_z_score Nullable(Float64),
rhr_baseline_sample_count UInt16,
rhr_baseline_coverage Float64,
rhr_mean_7d Nullable(Float64),
rhr_mean_previous_28d Nullable(Float64),
rr_mean_30d Nullable(Float64),
rr_sd_30d Nullable(Float64),
respiratory_rate_z_score Nullable(Float64),
rr_baseline_sample_count UInt16,
rr_baseline_coverage Float64,
rr_mean_7d Nullable(Float64),
rr_mean_previous_28d Nullable(Float64),
efficiency_mean_30d Nullable(Float64),
efficiency_sd_30d Nullable(Float64),
efficiency_z_score Nullable(Float64),
efficiency_baseline_sample_count UInt16,
efficiency_baseline_coverage Float64,
efficiency_mean_7d Nullable(Float64),
efficiency_mean_previous_28d Nullable(Float64),
hrv_mean_60d Nullable(Float64),
hrv_sd_60d Nullable(Float64),
rhr_mean_60d Nullable(Float64),
rhr_sd_60d Nullable(Float64),
hrv_score Nullable(Float64),
resting_hr_score Nullable(Float64),
sleep_score Nullable(Float64),
respiratory_rate_score Nullable(Float64),
is_deleted UInt8 DEFAULT 0,
refresh_version UInt64,
refreshed_at DateTime64(9)`,
    daily_body_measurement: `measurement_id UUID,
user_id UUID,
date Date,
recorded_at DateTime64(6, 'UTC'),
weight_kg Float64,
body_fat_pct Nullable(Float64),
is_deleted UInt8,
source_synced_at DateTime64(9, 'UTC'),
refresh_version UInt64,
refreshed_at DateTime64(9)`,
    v_body_measurement: `id UUID,
provider_id String,
user_id UUID,
external_id String,
recorded_at DateTime64(6, 'UTC'),
created_at DateTime64(9),
weight_kg Nullable(Float32),
body_fat_pct Nullable(Float32),
muscle_mass_kg Nullable(Float32),
bone_mass_kg Nullable(Float32),
water_pct Nullable(Float32),
bmi Nullable(Float32),
height_cm Nullable(Float32),
waist_circumference_cm Nullable(Float32),
systolic_bp Nullable(Int32),
diastolic_bp Nullable(Int32),
heart_pulse Nullable(Int32),
temperature_c Nullable(Float32),
source_name Nullable(String),
source_providers Array(String)`,
    v_daily_metrics: `date Date,
user_id UUID,
hrv Nullable(Float32),
spo2_avg Nullable(Float32),
respiratory_rate_avg Nullable(Float32),
skin_temp_c Nullable(Float32),
steps Nullable(Int32),
distance_km Nullable(Float32),
flights_climbed Nullable(Int32),
exercise_minutes Nullable(Int32),
stand_hours Nullable(Int32),
walking_speed Nullable(Float32),
walking_step_length Nullable(Float32),
walking_double_support_pct Nullable(Float32),
walking_asymmetry_pct Nullable(Float32),
walking_steadiness Nullable(Float32),
source_providers Array(String)`,
    provider_stats: `user_id UUID,
provider_id String,
activities UInt64,
daily_metrics UInt64,
sleep_sessions UInt64,
body_measurements UInt64,
food_entries UInt64,
health_events UInt64,
metric_stream UInt64,
nutrition_daily UInt64,
clinical_records UInt64,
journal_entries UInt64,
is_deleted UInt8,
refresh_version UInt64,
refreshed_at DateTime64(9)`,
    deduped_sensor: `user_id UUID,
recorded_at DateTime64(6, 'UTC'),
recorded_date Date,
channel String,
scalar Nullable(Float32),
provider_id Nullable(String),
source_metric_stream_id Nullable(UUID),
provider_priority UInt16,
refresh_version UInt64,
is_deleted UInt8,
refreshed_at DateTime64(9)`,
    deduped_location: `activity_id UUID,
user_id UUID,
recorded_at DateTime64(6, 'UTC'),
lat Nullable(Float32),
lng Nullable(Float32)`,
    deduped_activities: `activity_id UUID,
provider_id String,
user_id UUID,
canonical_type String,
provider_type String,
modality Nullable(String),
started_at DateTime64(6, 'UTC'),
ended_at Nullable(DateTime64(6, 'UTC')),
source_name Nullable(String),
name Nullable(String),
notes Nullable(String),
timezone Nullable(String),
start_utc_offset_minutes Nullable(Int16),
end_utc_offset_minutes Nullable(Int16),
local_time_source String,
raw Nullable(String),
source_synced_at DateTime64(9, 'UTC'),
source_providers Array(String),
source_external_ids Array(Map(String, Nullable(String))),
absent_source_external_ids Array(Map(String, Nullable(String))),
member_activity_ids Array(UUID),
refresh_version UInt64,
is_deleted UInt8,
refreshed_at DateTime64(9, 'UTC')`,
    activity_sensor_sample: `activity_id UUID,
user_id UUID,
recorded_at DateTime64(6, 'UTC'),
recorded_date Date,
channel String,
scalar Nullable(Float32),
refresh_version UInt64,
is_deleted UInt8,
refreshed_at DateTime64(9)`,
    activity_location_sample: `activity_id UUID,
user_id UUID,
recorded_at DateTime64(6, 'UTC'),
recorded_date Date,
source_metric_stream_id UUID,
lat Nullable(Float32),
lng Nullable(Float32),
refresh_version UInt64,
is_deleted UInt8,
refreshed_at Nullable(DateTime64(6, 'UTC'))`,
    activity_location_summary_rows: `activity_id UUID,
user_id UUID,
total_distance Nullable(Float64),
centroid_lat Nullable(Float64),
centroid_lng Nullable(Float64),
refresh_version UInt64,
is_deleted UInt8,
refreshed_at DateTime64(9)`,
    activity_stream_points: `user_id UUID,
activity_id UUID,
points Array(Tuple(recorded_at DateTime64(6, 'UTC'), heart_rate Nullable(Float64), power Nullable(Float64), speed Nullable(Float64), cadence Nullable(Float64), altitude Nullable(Float64), lat Nullable(Float64), lng Nullable(Float64))),
refresh_version UInt64,
is_deleted UInt8,
refreshed_at DateTime64(9)`,
    activity_heart_rate_zones: `user_id UUID,
activity_id UUID,
zones Array(Tuple(zone UInt8, seconds UInt32)),
refresh_version UInt64,
is_deleted UInt8,
refreshed_at DateTime64(9)`,
    activity_summary: `activity_id UUID,
user_id UUID,
canonical_type String,
provider_type Nullable(String),
modality Nullable(String),
name Nullable(String),
started_at DateTime64(6, 'UTC'),
ended_at Nullable(DateTime64(6, 'UTC')),
avg_hr Nullable(Float64),
max_hr Nullable(Int16),
min_hr Nullable(Int16),
avg_power Nullable(Float64),
max_power Nullable(Int16),
avg_speed Nullable(Float64),
max_speed Nullable(Float64),
avg_cadence Nullable(Float64),
elevation_gain_legacy Nullable(Float64),
total_distance Nullable(Float64),
centroid_lat Nullable(Float64),
centroid_lng Nullable(Float64),
avg_left_balance Nullable(Float64),
avg_left_torque_eff Nullable(Float64),
avg_right_torque_eff Nullable(Float64),
avg_left_pedal_smooth Nullable(Float64),
avg_right_pedal_smooth Nullable(Float64),
elevation_gain_m Nullable(Float64),
elevation_loss_m Nullable(Float64),
avg_stance_time Nullable(Float64),
avg_vertical_osc Nullable(Float64),
avg_ground_contact_time Nullable(Float64),
avg_stride_length Nullable(Float64),
sample_count UInt64,
hr_sample_count UInt64,
power_sample_count UInt64,
first_sample_at DateTime64(6, 'UTC'),
last_sample_at DateTime64(6, 'UTC'),
best_twenty_minute_power Nullable(Float64),
normalized_power Nullable(Float64),
smoothed_avg_power Nullable(Float64),
climbing_elevation_gain_m Nullable(Float64),
climbing_seconds Nullable(Int32),
refreshed_at DateTime64(9)`,
    hiking_activity: `activity_id UUID,
user_id UUID,
canonical_type String,
activity_name Nullable(String),
started_at DateTime64(6, 'UTC'),
ended_at Nullable(DateTime64(6, 'UTC')),
distance_m Float64,
duration_seconds Float64,
average_pace_min_per_km Float64,
elevation_gain_m Float64,
elevation_loss_m Float64,
average_grade_percent Float64,
avg_heart_rate Nullable(Float64),
is_deleted UInt8,
refresh_version UInt64,
refreshed_at DateTime64(9)`,
    daily_activity_load: `activity_id UUID,
user_id UUID,
started_at DateTime64(6, 'UTC'),
ended_at DateTime64(6, 'UTC'),
daily_load Nullable(Float64),
is_deleted UInt8,
refresh_version UInt64,
refreshed_at DateTime64(9)`,
    daily_endurance_load: `activity_id UUID,
user_id UUID,
started_at Nullable(DateTime64(6, 'UTC')),
ended_at Nullable(DateTime64(6, 'UTC')),
date Nullable(Date),
training_load Float64,
is_deleted UInt8,
refresh_version UInt64,
refreshed_at DateTime64(9)`,
    weekly_endurance_ramp_rate: `user_id UUID,
week Date,
ctl_start Float64,
ctl_end Float64,
ramp_rate Float64,
is_deleted UInt8,
refresh_version UInt64,
refreshed_at DateTime64(9)`,
    weekly_training_monotony: `user_id UUID,
week Date,
monotony Float64,
strain Float64,
weekly_load Float64,
is_deleted UInt8,
refresh_version UInt64,
refreshed_at DateTime64(9)`,
    daily_strain: `user_id UUID,
date Date,
daily_load Float64,
strain Float64,
acute_load_7d Float64,
chronic_load_28d Float64,
workload_ratio Nullable(Float64),
is_deleted UInt8,
refresh_version UInt64,
refreshed_at DateTime64(9)`,
    healthspan_activity_zone_minutes: `activity_id UUID,
user_id UUID,
started_at DateTime64(6, 'UTC'),
ended_at DateTime64(6, 'UTC'),
aerobic_minutes Float64,
high_intensity_minutes Float64,
is_deleted UInt8,
refresh_version UInt64,
refreshed_at DateTime64(9)`,
    weekly_healthspan: `user_id UUID,
week_start Date,
avg_sleep_min Nullable(Float64),
bedtime_stddev_min Nullable(Float64),
avg_resting_hr Nullable(Float64),
avg_steps Nullable(Float64),
latest_vo2max Nullable(Float64),
weekly_aerobic_min Float64,
weekly_high_intensity_min Float64,
sessions_per_week Nullable(Float64),
weight_kg Nullable(Float64),
body_fat_pct Nullable(Float64),
refresh_version UInt64,
refreshed_at DateTime64(9)`,
    activity_trend_daily: `user_id UUID,
bucket_date Date,
avg_hr Nullable(Float64),
max_hr Nullable(Int16),
avg_power Nullable(Float64),
max_power Nullable(Int16),
avg_cadence Nullable(Float64),
avg_speed Nullable(Float64),
total_samples UInt64,
hr_samples UInt64,
power_samples UInt64,
cadence_samples UInt64,
speed_samples UInt64,
activity_count UInt64`,
    activity_power_curve: `activity_id UUID,
user_id UUID,
started_at Nullable(DateTime64(6, 'UTC')),
activity_date Nullable(String),
duration_seconds Int32,
best_power Nullable(Int32),
is_deleted UInt8,
refresh_version UInt64,
refreshed_at DateTime64(9)`,
    activity_aerobic_efficiency: `activity_id UUID,
user_id UUID,
canonical_type String,
name Nullable(String),
started_at DateTime64(6, 'UTC'),
ended_at Nullable(DateTime64(6, 'UTC')),
max_hr Nullable(Int16),
resting_hr Nullable(Float64),
avg_power_z2 Float64,
avg_hr_z2 Float64,
efficiency_factor Float64,
z2_samples Int32,
is_deleted UInt8,
refresh_version UInt64,
refreshed_at DateTime64(9)`,
    cycling_activity: `activity_id UUID,
user_id UUID,
provider_id String,
source_providers Array(String),
canonical_type String,
provider_type Nullable(String),
modality Nullable(String),
activity_name Nullable(String),
started_at DateTime64(6, 'UTC'),
ended_at Nullable(DateTime64(6, 'UTC')),
distance_meters Nullable(Float64),
average_heart_rate Nullable(Float64),
max_heart_rate Nullable(Float64),
average_power Nullable(Float64),
power_samples UInt64,
heart_rate_samples UInt64,
normalized_power Nullable(Float64),
best_twenty_minute_power Nullable(Float64),
elevation_gain_meters Nullable(Float64),
elapsed_seconds Int32,
efficiency_max_heart_rate Nullable(Float64),
average_power_zone_two Nullable(Float64),
average_heart_rate_zone_two Nullable(Float64),
efficiency_factor Nullable(Float64),
zone_two_samples Nullable(Int32),
is_deleted UInt8,
refresh_version UInt64,
refreshed_at DateTime64(9, 'UTC')`,
    daily_cycling: `user_id UUID,
date Date,
activities Array(Tuple(UUID, DateTime64(6, 'UTC'), Float64, Float64, Float64, Nullable(Float64), UInt64, UInt64, Nullable(Float64), Nullable(String))),
is_deleted UInt8,
refresh_version UInt64,
refreshed_at DateTime64(9, 'UTC')`,
    activity_polarization_zones: `activity_id UUID,
user_id UUID,
canonical_type String,
started_at DateTime64(6, 'UTC'),
max_hr Nullable(Int16),
z1_seconds Int32,
z2_seconds Int32,
z3_seconds Int32,
is_deleted UInt8,
refresh_version UInt64,
refreshed_at DateTime64(9)`,
  };
  const shortViewName = viewName.split(".").at(-1);
  if (!shortViewName) {
    throw new Error(`Missing ClickHouse test analytics table name for ${viewName}`);
  }
  if (shortViewName === "activity_sensor_summary_rows") {
    return buildActivitySensorSummaryRowsTableSql().replace(
      "analytics.activity_sensor_summary_rows",
      viewName,
    );
  }
  const columnDefinitions = columnDefinitionsByViewName[shortViewName];
  if (!columnDefinitions) {
    throw new Error(`Missing ClickHouse test analytics table schema for ${viewName}`);
  }
  const engine =
    shortViewName === "deduped_activities" ||
    shortViewName === "activity_sensor_sample" ||
    shortViewName === "activity_location_sample" ||
    shortViewName === "activity_sensor_summary_rows" ||
    shortViewName === "activity_location_summary_rows" ||
    shortViewName === "activity_stream_points" ||
    shortViewName === "activity_heart_rate_zones" ||
    shortViewName === "daily_sleep" ||
    shortViewName === "daily_recovery_inputs" ||
    shortViewName === "daily_recovery" ||
    shortViewName === "daily_body_measurement" ||
    shortViewName === "daily_endurance_load" ||
    shortViewName === "daily_activity_load" ||
    shortViewName === "weekly_endurance_ramp_rate" ||
    shortViewName === "weekly_training_monotony" ||
    shortViewName === "daily_strain" ||
    shortViewName === "healthspan_activity_zone_minutes" ||
    shortViewName === "weekly_healthspan" ||
    shortViewName === "provider_stats" ||
    shortViewName === "hiking_activity" ||
    shortViewName === "activity_power_curve" ||
    shortViewName === "activity_aerobic_efficiency" ||
    shortViewName === "cycling_activity" ||
    shortViewName === "daily_cycling" ||
    shortViewName === "activity_polarization_zones"
      ? "ReplacingMergeTree(refresh_version)"
      : "MergeTree";
  const orderBy =
    shortViewName === "deduped_activities"
      ? "(user_id, activity_id)"
      : shortViewName === "activity_sensor_sample"
        ? "(user_id, activity_id, recorded_date, channel, recorded_at)"
        : shortViewName === "activity_location_sample"
          ? "(user_id, activity_id, recorded_date, recorded_at, source_metric_stream_id)"
          : shortViewName === "activity_sensor_summary_rows" ||
              shortViewName === "activity_location_summary_rows" ||
              shortViewName === "activity_stream_points" ||
              shortViewName === "activity_heart_rate_zones"
            ? "(user_id, activity_id)"
            : shortViewName === "daily_sleep" || shortViewName === "daily_recovery_inputs"
              ? "(user_id, date)"
              : shortViewName === "daily_recovery"
                ? "(user_id, date)"
                : shortViewName === "daily_body_measurement"
                  ? "(user_id, measurement_id)"
                  : shortViewName === "daily_endurance_load" ||
                      shortViewName === "daily_activity_load" ||
                      shortViewName === "healthspan_activity_zone_minutes"
                    ? "(user_id, activity_id)"
                    : shortViewName === "weekly_endurance_ramp_rate" ||
                        shortViewName === "weekly_training_monotony"
                      ? "(user_id, week)"
                      : shortViewName === "daily_strain"
                        ? "(user_id, date)"
                        : shortViewName === "weekly_healthspan"
                          ? "(user_id, week_start)"
                          : shortViewName === "provider_stats"
                            ? "(user_id, provider_id)"
                            : shortViewName === "activity_power_curve"
                              ? "(user_id, activity_id, duration_seconds)"
                              : shortViewName === "hiking_activity" ||
                                  shortViewName === "activity_aerobic_efficiency" ||
                                  shortViewName === "activity_polarization_zones"
                                ? "(user_id, activity_id)"
                                : shortViewName === "cycling_activity"
                                  ? "(user_id, activity_id)"
                                  : shortViewName === "daily_cycling"
                                    ? "(user_id, date)"
                                    : "tuple()";
  return `CREATE TABLE IF NOT EXISTS ${viewName} (
${columnDefinitions}
)
ENGINE = ${engine}
ORDER BY ${orderBy}`;
}
