// ============================================================
// Sport ID mapping — complete list from WHOOP developer docs
// ============================================================

const WHOOP_SPORT_MAP: Record<number, string> = {
  [-1]: "other",
  0: "running",
  1: "cycling",
  16: "baseball",
  17: "basketball",
  18: "rowing",
  19: "fencing",
  20: "field hockey",
  21: "football",
  22: "golf",
  24: "ice hockey",
  25: "lacrosse",
  27: "rugby",
  28: "sailing",
  29: "skiing",
  30: "soccer",
  31: "softball",
  32: "squash",
  33: "swimming",
  34: "tennis",
  35: "track & field",
  36: "volleyball",
  37: "water polo",
  38: "wrestling",
  39: "boxing",
  42: "dance",
  43: "pilates",
  44: "yoga",
  45: "weightlifting",
  47: "cross country skiing",
  48: "functional fitness",
  49: "duathlon",
  51: "gymnastics",
  52: "hiking",
  53: "horseback riding",
  55: "kayaking",
  56: "martial arts",
  57: "mountain biking",
  59: "powerlifting",
  60: "rock climbing",
  61: "paddleboarding",
  62: "triathlon",
  63: "walking",
  64: "surfing",
  65: "elliptical",
  66: "stairmaster",
  70: "meditation",
  71: "other",
  73: "diving",
  74: "operations - tactical",
  75: "operations - medical",
  76: "operations - flying",
  77: "operations - water",
  82: "ultimate",
  83: "climber",
  84: "jumping rope",
  85: "australian football",
  86: "skateboarding",
  87: "coaching",
  88: "ice bath",
  89: "commuting",
  90: "gaming",
  91: "snowboarding",
  92: "motocross",
  93: "caddying",
  94: "obstacle course racing",
  95: "motor racing",
  96: "hiit",
  97: "spin",
  98: "jiu jitsu",
  99: "manual labor",
  100: "cricket",
  101: "paddle ball",
  102: "inline skating",
  103: "box fitness",
  104: "spikeball",
  105: "wheelchair pushing",
  106: "paddle tennis",
  107: "barre",
  108: "stage performance",
  109: "high stress work",
  110: "parkour",
  111: "gaelic football",
  112: "hurling",
  113: "circus arts",
  121: "massage therapy",
  123: "strength trainer",
  125: "watching sports",
  126: "assault bike",
  127: "kickboxing",
  128: "stretching",
  230: "table tennis",
  231: "badminton",
  232: "netball",
  233: "sauna",
  234: "disc golf",
  235: "yard work",
  236: "air compression",
  237: "percussive massage",
  238: "paintball",
  239: "ice skating",
  240: "handball",
  248: "f45 training",
  249: "padel",
  250: "barry's",
  251: "dedicated parenting",
  252: "stroller walking",
  253: "stroller jogging",
  254: "toddlerwearing",
  255: "babywearing",
  258: "barre3",
  259: "hot yoga",
  261: "stadium steps",
  262: "polo",
  263: "musical performance",
  264: "kite boarding",
  266: "dog walking",
  267: "water skiing",
  268: "wakeboarding",
  269: "cooking",
  270: "cleaning",
  272: "public speaking",
};

/**
 * Map a WHOOP sport_id to a human-readable activity name.
 * Returns "other" for unknown sport IDs.
 */
export function mapSportId(sportId: number): string {
  return WHOOP_SPORT_MAP[sportId] ?? "other";
}

/** All known WHOOP sport IDs and their names. */
export { WHOOP_SPORT_MAP };
