import type { CanonicalActivityType } from "@dofek/training/training";

// ============================================================
// Sport ID mapping — complete list from WHOOP developer docs
// ============================================================

const WHOOP_SPORT_MAP: Record<number, CanonicalActivityType> = {
  [-1]: "other",
  0: "running",
  1: "cycling",
  16: "baseball",
  17: "basketball",
  18: "rowing",
  19: "fencing",
  20: "hockey",
  21: "football",
  22: "golf",
  24: "ice_hockey",
  25: "lacrosse",
  27: "rugby",
  28: "sailing",
  29: "skiing",
  30: "soccer",
  31: "softball",
  32: "squash",
  33: "swimming",
  34: "tennis",
  35: "track_and_field",
  36: "volleyball",
  37: "water_polo",
  38: "wrestling",
  39: "boxing",
  42: "dance",
  43: "pilates",
  44: "yoga",
  45: "strength",
  47: "cross_country_skiing",
  48: "functional_fitness",
  49: "triathlon",
  51: "gymnastics",
  52: "hiking",
  53: "equestrian",
  55: "kayaking",
  56: "martial_arts",
  57: "mountain_biking",
  59: "strength",
  60: "rock_climbing",
  61: "paddleboarding",
  62: "triathlon",
  63: "walking",
  64: "surfing",
  65: "elliptical",
  66: "stairmaster",
  70: "meditation",
  71: "other",
  73: "underwater_diving",
  74: "other",
  75: "other",
  76: "other",
  77: "other",
  82: "other",
  83: "climbing",
  84: "jump_rope",
  85: "australian_football",
  86: "skating",
  87: "other",
  88: "other",
  89: "other",
  90: "fitness_gaming",
  91: "snowboarding",
  92: "other",
  93: "other",
  94: "cross_training",
  95: "other",
  96: "hiit",
  97: "indoor_cycling",
  98: "martial_arts",
  99: "other",
  100: "cricket",
  101: "paddle_racquet",
  102: "skating",
  103: "boxing",
  104: "other",
  105: "wheelchair_walk",
  106: "paddle_racquet",
  107: "barre",
  108: "other",
  109: "other",
  110: "other",
  111: "football",
  112: "other",
  113: "other",
  121: "other",
  123: "strength",
  125: "other",
  126: "cardio",
  127: "kickboxing",
  128: "stretching",
  230: "table_tennis",
  231: "badminton",
  232: "other",
  233: "other",
  234: "disc_golf",
  235: "other",
  236: "other",
  237: "other",
  238: "other",
  239: "skating",
  240: "handball",
  248: "cross_training",
  249: "padel",
  250: "cross_training",
  251: "other",
  252: "walking",
  253: "running",
  254: "other",
  255: "other",
  258: "barre",
  259: "yoga",
  261: "stair_climbing",
  262: "equestrian",
  263: "other",
  264: "water_sports",
  266: "walking",
  267: "water_sports",
  268: "water_sports",
  269: "other",
  270: "other",
  272: "other",
};

/**
 * Map a WHOOP sport_id to a canonical activity type.
 * Returns "other" for unknown sport IDs.
 */
export function mapSportId(sportId: number): CanonicalActivityType {
  return WHOOP_SPORT_MAP[sportId] ?? "other";
}

// ============================================================
// v2_activity type name → canonical activity type
// ============================================================
// The BFF cycle response includes `v2_activities[]` with a human-readable
// `type` string (e.g., "walk", "spin", "functional-fitness"). This map
// provides a fallback when a sport_id is unknown or maps to "other".

const V2_ACTIVITY_TYPE_MAP: Record<string, CanonicalActivityType> = {
  walk: "walking",
  walking: "walking",
  "dog-walk": "walking",
  "dog-walking": "walking",
  "stroller-walk": "walking",
  "stroller-walking": "walking",
  run: "running",
  running: "running",
  "stroller-jogging": "running",
  cycling: "cycling",
  spin: "indoor_cycling",
  "indoor-cycling": "indoor_cycling",
  "mountain-biking": "mountain_biking",
  swimming: "swimming",
  hiking: "hiking",
  rucking: "hiking",
  yoga: "yoga",
  "hot-yoga": "yoga",
  pilates: "pilates",
  strength: "strength",
  weightlifting: "strength",
  "strength-trainer": "strength",
  "functional-fitness": "functional_fitness",
  rowing: "rowing",
  elliptical: "elliptical",
  stairmaster: "stairmaster",
  "stair-climbing": "stair_climbing",
  "stadium-steps": "stair_climbing",
  meditation: "meditation",
  boxing: "boxing",
  "box-fitness": "boxing",
  kickboxing: "kickboxing",
  "martial-arts": "martial_arts",
  "jiu-jitsu": "martial_arts",
  tennis: "tennis",
  basketball: "basketball",
  soccer: "soccer",
  golf: "golf",
  "ice-hockey": "ice_hockey",
  baseball: "baseball",
  softball: "softball",
  volleyball: "volleyball",
  squash: "squash",
  wrestling: "wrestling",
  lacrosse: "lacrosse",
  rugby: "rugby",
  cricket: "cricket",
  handball: "handball",
  badminton: "badminton",
  "table-tennis": "table_tennis",
  pickleball: "paddle_racquet",
  "paddle-tennis": "paddle_racquet",
  padel: "padel",
  surfing: "surfing",
  snowboarding: "snowboarding",
  skiing: "skiing",
  "cross-country-skiing": "cross_country_skiing",
  "rock-climbing": "rock_climbing",
  climbing: "climbing",
  gymnastics: "gymnastics",
  dance: "dance",
  skating: "skating",
  "ice-skating": "skating",
  "inline-skating": "skating",
  kayaking: "kayaking",
  paddleboarding: "paddleboarding",
  sailing: "sailing",
  fencing: "fencing",
  "track-and-field": "track_and_field",
  triathlon: "triathlon",
  duathlon: "triathlon",
  hiit: "hiit",
  "obstacle-course-racing": "cross_training",
  "cross-training": "cross_training",
  "f45-training": "cross_training",
  barrys: "cross_training",
  stretching: "stretching",
  barre: "barre",
  barre3: "barre",
  "jump-rope": "jump_rope",
  "jumping-rope": "jump_rope",
  "water-polo": "water_polo",
  "water-sports": "water_sports",
  "kite-boarding": "water_sports",
  "water-skiing": "water_sports",
  wakeboarding: "water_sports",
  diving: "underwater_diving",
  "disc-golf": "disc_golf",
  "fitness-gaming": "fitness_gaming",
  football: "football",
  "gaelic-football": "football",
  "australian-football": "australian_football",
  "horseback-riding": "equestrian",
  polo: "equestrian",
  cardio: "cardio",
  "assault-bike": "cardio",
  breathwork: "breathwork",
};

/**
 * Map a WHOOP v2_activity type string to a canonical activity type.
 * Returns null if the type is unknown (caller should fall back to sport_id).
 */
export function mapV2ActivityType(typeName: string): CanonicalActivityType | null {
  return V2_ACTIVITY_TYPE_MAP[typeName.toLowerCase()] ?? null;
}

/** All known WHOOP sport IDs and their canonical types. */
export { WHOOP_SPORT_MAP };
