name: Build + Deploy

on:
  workflow_dispatch:
    inputs:
      target:
        description: "Target: web = deploy infra + web stack, web-stack = deploy web stack only"
        type: choice
        required: true
        options:
          - web
          - web-stack

jobs:
  deploy:
    name: Build + Deploy
    permissions:
      actions: read
      contents: read
      id-token: write
      packages: write
    uses: ./.github/workflows/deploy.yml
    with:
      target: ${{ inputs.target }}
    secrets: inherit
