name: Build + Deploy

on:
  workflow_dispatch:
    inputs:
      target:
        description: "Target: web = deploy infra + app, app = deploy app only"
        type: choice
        required: true
        options:
          - web
          - app

jobs:
  deploy:
    name: Build + Deploy
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/deploy.yml
    with:
      target: ${{ inputs.target }}
    secrets: inherit
