name: Build Mobile Storybook

on:
  workflow_call:

jobs:
  build:
    name: Build Mobile Storybook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: ./.github/actions/setup-node-pnpm
      - name: Build Mobile Storybook
        run: pnpm storybook:mobile:build
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: storybook-mobile-build
          path: packages/mobile/storybook-static/
          retention-days: 7
