name: Deploy Cloudflare

on:
  workflow_call:
    inputs:
      commit_sha:
        description: "Commit SHA to deploy"
        required: true
        type: string
  workflow_dispatch:
    inputs:
      commit_sha:
        description: "Commit SHA to deploy (defaults to workflow ref HEAD)"
        required: false
        type: string

jobs:
  cloudflare:
    name: Deploy Cloudflare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: ${{ inputs.commit_sha != '' && inputs.commit_sha || github.sha }}
      - uses: hashicorp/setup-terraform@5e8dbf3c6d9deaf4193ca7a8fb23f2ac83bb6c85 # v4
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: Terraform Apply
        working-directory: deploy/cloudflare
        env:
          TF_VAR_cloudflare_api_token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          TF_VAR_cloudflare_account_id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          TF_VAR_server_ip: ${{ secrets.SERVER_HOST }}
        run: |
          terraform init
          terraform apply -auto-approve
